name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "1.21"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        export PATH="$HOME/go/bin:$PATH"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Format
      run: if [ "$(goimports -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      if: matrix.go-version == 1.21
